app/urls.py
from django.urls import path
from . import views

app_name = 'app'


urlpatterns = [
    
    path('',views.index, name='index'),
    path('dashboard/',views.dashboard, name='dashboard'),


    path('about/',views.create_about, name='about'),
    path('edit-about/',views.edit_about, name='edit-about'),
    path('delete-about/<str:id>',views.delete_about, name='delete-about'),

    path('testmony/',views.create_testmony, name='testmony'),
    path('edit-testmony/<str:id>',views.edit_testmony, name='edit-testmony'),
    path('delete-testmony/<str:id>',views.delete_testmony, name='delete-testmony'),
    
    path('service/',views.create_service, name='service'),
    path('edit-service/<str:id>',views.edit_service, name='edit-service'),
    path('delete-service/<str:id>',views.delete_service, name='delete-service'),

    path('settings/',views.create_settings, name='settings'),
    path('edit-settings/',views.edit_settings, name='edit-settings'),
    path('delete-settings/<str:id>',views.delete_settings, name='delete-settings'),

    path('team/',views.create_team, name='team'),
    path('edit-team/<str:id>',views.edit_team, name='edit-team'),
    path('delete-team/<str:id>',views.delete_team, name='delete-team'),

    path('order/',views.list_order, name='order'),
    path('create-order/',views.create_order, name='create-order'),
    path('confirm-order/<str:id>',views.confirm_order, name='confirm_order'),
    path('complete-order/<str:id>',views.complete_order, name='complete_order'),
    path('cancel-order/<str:id>',views.cancel_order, name='cancel_order'),
    path('view-order/<str:id>',views.view_order, name='view_order_details'),


    path('hero/',views.create_hero, name='hero'),
    path('edit-hero/',views.edit_hero, name='edit-hero'),
    path('delete-hero/<str:id>',views.delete_hero, name='delete-hero'),
    path('edit-hero-image/<str:id>',views.edit_hero_image, name='edit_image'),

    path('social-links/',views.create_link, name='social'),
    path('edit-social-links/<str:id>',views.edit_link, name='edit-social'),
    path('delete-social-links/<str:id>',views.delete_link, name='delete-social'),


    path('aboutus/',views.get_about, name='aboutus'),
    path('product/',views.get_product, name='product'),
    path('our-services/',views.get_service, name='services'),
   

]

ccw/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('account/',include('account.urls', namespace='account')),
    path('',include('app.urls', namespace='app')),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

app/templates/category/edit.html
{% extends "master.html" %} {% load widget_tweaks %} {% block content %}
 <!-- start page title -->
<div class="row">
    <div class="col-12">
        <div class="page-title-box">
            <div class="page-title-right">
                <ol class="breadcrumb m-0">
                    <li class="breadcrumb-item"><a href="{% url 'app:dashboard' %}">Dashboard</a></li>
                    <li class="breadcrumb-item active">Hero</li>
                </ol>
            </div>
            <h4 class="page-title">Hero</h4>
        </div>
    </div>
</div>     
<!-- end page title --> 

<!--  -->


<div class="row justify-content-center">
     {% include 'includes/alert.html' %}
    <div class="col-lg-8 mt-3">
        <div class="card">
            <div class="card-body">
                <h4 class="header-title">{{title}}</h4>
                <p class="sub-header">

                </p>
                <form action="" method="post" enctype="multipart/form-data">
                {% csrf_token%}
                {% for hidden in form.hidden_fields %} 
                {{ hidden }} 
                {% endfor %}


                {% for field in form.visible_fields %}
                <div class="mb-3">
                    <label for="fullname" class="form-label">{{ field.label }}</label>
                    {{ field|add_class:'form-control' }}
                </div>
                {% endfor %}





                <div class="text-center d-grid">
                    <button class="btn btn-success" type="submit"> Save  </button>
                </div>

            </form>

            </div>
        </div>
    </div>
</div>
{% endblock content %}

app/templates/category/list.html
{% extends 'master.html' %}
{% load static %}
{% load widget_tweaks %} 

{% block content %}


<!-- start page title -->
<div class="row">
    <div class="col-12">
        <div class="page-title-box">
            <div class="page-title-right">
                <ol class="breadcrumb m-0">
                    <li class="breadcrumb-item"><a href="{% url 'app:dashboard' %}">Dashboard</a></li>
                    <li class="breadcrumb-item active">Hero</li>
                </ol>
            </div>
            <h4 class="page-title">Hero</h4>
        </div>
    </div>
</div>     
<!-- end page title --> 


<div class="row">
     {% include 'includes/alert.html' %}
    <div class="col-12 mt-3">
        <div class="card">
            <div class="card-body">
                <div class="row justify-content-between">
                    <div class="col-md-8">

                    </div>
                    <div class="col-md-4">
                        <div class="text-md-end mt-3 mt-md-0">
                            <button type="button" class="btn btn-success waves-effect waves-light me-1"><i class="mdi mdi-cog"></i></button>
                            {% if not hero %}

                            <button type="button" class="btn btn-danger waves-effect waves-light me-1" data-bs-toggle="modal" data-bs-target="#custom-modal"><i class="mdi mdi-plus-circle me-1"></i> New Hero</button>

                            {% endif %}
    
                        </div>
                    </div><!-- end col-->
                </div> <!-- end row -->

            </div>
        </div> <!-- end card -->
    </div><!-- end col-->




</div>
<!-- end row --> 
    
    {% if hero %}

    <div class="row justify-content-center">
    <div class="col-lg-8 just">
        <div class="card bg-pattern">
            <div class="card-body">
                <div class="text-center">
                    <img src="{{hero.hero_image.url}}" alt="logo" class="avatar-xl rounded-circle mb-3">
                    {% comment %} <h4 class="mb-1 font-18">{{setting.name}}</h4>
                    <p class="text-muted  font-14">{{setting.location}}</p> {% endcomment %}
                </div>


                <div class="text-center">
                
                    <a href="{% url 'app:edit-hero' %}" class="btn btn-sm btn-primary">Edit</a>
                </div>

            </div>
        </div> <!-- end card -->
    </div><!-- end col -->
</div>

 <div class="row justify-content-between mt-3">

        <div class="table-responsive">

                     <table id="selection-datatable" class="table dt-responsive nowrap w-100">
                        <thead>
                            <tr>
                                <th>Image</th>
                                <th>Action</th>
                            </tr>
                        </thead>


                        <tbody>

                              
                       {% for data in hero_images  %}
                            <tr>
                                    {% if data.hero_image %}
                                <td><img src="{{data.hero_image.url}}" alt="logo" class="avatar-xl rounded-circle mb-3"></td>
                                    <td>
                                        <a href="{% url 'app:edit_image' data.id %}" class="action-icon" data-bs-toggle="tooltip" data-bs-placement="top" title="Edit"> <i class="mdi mdi-pencil"></i></a>

                                    </td>
                                    {% endif %}
                                    
                            </tr>
                        {% endfor %}


                        </tbody>
                        </table>

                </div>

    </div>
        
    {% endif %}
          

<!-- end row -->



 <!-- Modal -->
        <div class="modal fade" id="custom-modal" tabindex="-1" role="dialog" aria-hidden="true">
            <div class="modal-dialog modal-dialog-centered">
                <div class="modal-content">
                    <div class="modal-header bg-light">
                        <h4 class="modal-title" id="myCenterModalLabel">{{title}}</h4>
                        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                    </div>
                    <div class="modal-body p-4">
                        <form action="" method="post" enctype="multipart/form-data">
                            {% csrf_token %}
                             {% for hidden in form.hidden_fields %} 
                            {{ hidden }} 
                            {% endfor %}
                           {% for field in form.visible_fields %}
                            <div class="mb-3">
                        <label for="{{ field.id_for_label }}" class="form-label">{{ field.label }}<span
                                class="text-danger">*</span></label> {{ field|add_class:'form-control' }} {% for error in field.errors %}
                        <ul class="parsley-errors-list filled" id="parsley-id-27" aria-hidden="false">
                            <li class="parsley-required">{{ error }}</li>
                        </ul>
                        {% endfor %}

                    </div>
                            {% endfor %}

                            {{ formset.management_form }}
                            {% for form in formset %}
                                {{ form }}
                            {% endfor %}


                            <div class="text-end">
                                <button type="submit" class="btn btn-success waves-effect waves-light">Save</button>
                             
                            </div>
                        </form>
                    </div>
                </div><!-- /.modal-content -->
            </div><!-- /.modal-dialog -->
        </div><!-- /.modal -->


{% endblock content %}