app/urls.py
from django.urls import path
from . import views

app_name = 'app'


urlpatterns = [
    
    path('',views.index, name='index'),
    path('dashboard/',views.dashboard, name='dashboard'),


    path('about/',views.create_about, name='about'),
    path('edit-about/',views.edit_about, name='edit-about'),
    path('delete-about/<str:id>',views.delete_about, name='delete-about'),

    path('testmony/',views.create_testmony, name='testmony'),
    path('edit-testmony/<str:id>',views.edit_testmony, name='edit-testmony'),
    path('delete-testmony/<str:id>',views.delete_testmony, name='delete-testmony'),
    
    path('service/',views.create_service, name='service'),
    path('edit-service/<str:id>',views.edit_service, name='edit-service'),
    path('delete-service/<str:id>',views.delete_service, name='delete-service'),

    path('settings/',views.create_settings, name='settings'),
    path('edit-settings/',views.edit_settings, name='edit-settings'),
    path('delete-settings/<str:id>',views.delete_settings, name='delete-settings'),

    path('team/',views.create_team, name='team'),
    path('edit-team/<str:id>',views.edit_team, name='edit-team'),
    path('delete-team/<str:id>',views.delete_team, name='delete-team'),

    path('order/',views.list_order, name='order'),
    path('create-order/',views.create_order, name='create-order'),
    path('confirm-order/<str:id>',views.confirm_order, name='confirm_order'),
    path('complete-order/<str:id>',views.complete_order, name='complete_order'),
    path('cancel-order/<str:id>',views.cancel_order, name='cancel_order'),
    path('view-order/<str:id>',views.view_order, name='view_order_details'),


    path('hero/',views.create_hero, name='hero'),
    path('edit-hero/',views.edit_hero, name='edit-hero'),
    path('delete-hero/<str:id>',views.delete_hero, name='delete-hero'),
    path('edit-hero-image/<str:id>',views.edit_hero_image, name='edit_image'),

    path('social-links/',views.create_link, name='social'),
    path('edit-social-links/<str:id>',views.edit_link, name='edit-social'),
    path('delete-social-links/<str:id>',views.delete_link, name='delete-social'),


    path('aboutus/',views.get_about, name='aboutus'),
    path('product/',views.get_product, name='product'),
    path('our-services/',views.get_service, name='services'),
   

]

ccw/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('account/',include('account.urls', namespace='account')),
    path('',include('app.urls', namespace='app')),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

app/templates/order/list.html
{% extends 'master.html' %}
{% load static %}
{% load widget_tweaks %} 

{% block content %}


 <!-- start page title -->
<div class="row">
    <div class="col-12">
        <div class="page-title-box">
            <div class="page-title-right">
                <ol class="breadcrumb m-0">
                    <li class="breadcrumb-item"><a href="{% url 'app:dashboard' %}">Dashboard</a></li>
                    <li class="breadcrumb-item active">Order</li>
                </ol>
            </div>
            <h4 class="page-title">Orders</h4>
        </div>
    </div>
</div>     
<!-- end page title --> 
<div class="row">
    {% include 'includes/alert.html' %}
    <div class="col-lg-12 mt-3">
        <div class="card">
            <div class="card-body">
                <div class="row justify-content-between mb-2">
                    <div class="col-auto">
                       
                    </div>
                    <div class="col-sm-6">
                        <div class="text-sm-end">
                            <button type="button" class="btn btn-success waves-effect waves-light mb-2 me-1"  data-bs-toggle="modal" data-bs-target="#standard-modal" data-bs-placement="top" data-bs-title="Filter"><i class="mdi mdi-filter" data-bs-toggle="tooltip"  data-bs-placement="top" data-bs-title="Filter"></i></button>
                            {% comment %} <button type="button" class="btn btn-danger waves-effect waves-light mb-2" data-bs-toggle="modal" data-bs-target="#custom-modal">Add Contact</button> {% endcomment %}
                        </div>
                    </div><!-- end col-->
                </div>

                <div class="table-responsive">

                     <table id="selection-datatable" class="table dt-responsive nowrap w-100">
                        <thead>
                            <tr>
                                <th>Customer</th>
                                <th>Service</th>
                                <th>Start Date</th>
                                <th>Delivery Date</th>
                                <th>Status</th>
                                <th>Received By</th>
                                <th>Created at</th>
                                <th>Action</th>
                            </tr>
                        </thead>
                    
                    
                        <tbody>

                       {% for data in order  %}
                            <tr>
                                <td>{{data.fullname}}</td>
                                <td> {{data.service}}</td>
                                <td> {{data.date_start}}</td>
                                <td> {{data.date_delivery}}</td>
                                <td> {{data.status}}</td>
                                <td> {{data.received_by}}</td> 
                                <td> {{data.created_date}}</td>
                                    <td>
                                        
                                        
                                        {% if not data.status == "Delivery" %}
                                        <a href="{% url 'app:confirm_order' data.id %}" class="action-icon" data-bs-toggle="tooltip" data-bs-placement="top" title="Accept Order"> <i class="mdi mdi-checkbox-multiple-marked"></i></a>
                                         <a href="{% url 'app:cancel_order' data.id %}" class="action-icon" data-bs-toggle="tooltip" data-bs-placement="top" title="Cancel Order"> <i class="mdi mdi-cancel"></i></a>
                                         <a href="{% url 'app:complete_order' data.id %}" class="action-icon" data-bs-toggle="tooltip" data-bs-placement="top" title="Complete and Deliver Order"> <i class="mdi mdi-truck-delivery"></i></a>
                                        {% endif %}
                                        <a href="{% url 'app:view_order_details' data.id %}" class="action-icon" data-bs-toggle="tooltip" data-bs-placement="top" title="Order Details"> <i class="mdi mdi-eye"></i></a>
                                            
                                       
                                    </td>
                            </tr>
                        {% endfor %}
                            
                        </tbody>
                        </table>






                  
                </div>


            </div> <!-- end card-body-->
        </div> <!-- end card-->
    </div> <!-- end col -->

    </div>
</div>
<!-- end row -->


 <!-- Modal -->
        <div class="modal fade" id="custom-modal" tabindex="-1" role="dialog" aria-hidden="true">
            <div class="modal-dialog modal-dialog-centered">
                <div class="modal-content">
                    <div class="modal-header bg-light">
                        <h4 class="modal-title" id="myCenterModalLabel">Add Contacts</h4>
                        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                    </div>
                    <div class="modal-body p-4">
                        <form action="" method="post">
                            {% csrf_token %}
                             {% for hidden in form.hidden_fields %} 
                            {{ hidden }} 
                            {% endfor %}
                           {% for field in form.visible_fields %}
                            <div class="mb-3">
                        <label for="{{ field.id_for_label }}" class="form-label">{{ field.label }}<span
                                class="text-danger">*</span></label> {{ field|add_class:'form-control' }} {% for error in field.errors %}
                        <ul class="parsley-errors-list filled" id="parsley-id-27" aria-hidden="false">
                            <li class="parsley-required">{{ error }}</li>
                        </ul>
                        {% endfor %}
                    </div>
                            {% endfor %}
                            <div class="text-end">
                                <button type="submit" class="btn btn-success waves-effect waves-light">Save</button>
                             
                            </div>
                        </form>
                    </div>
                </div><!-- /.modal-content -->
            </div><!-- /.modal-dialog -->
        </div><!-- /.modal -->

{% endblock content %}

app/templates/order/view.html
{% extends 'master.html' %}
{% load static %}
{% block content %}

<div class="row">
    <div class="col-12">
        <div class="page-title-box">
            <div class="page-title-right">
                <ol class="breadcrumb m-0">
                    <li class="breadcrumb-item"><a href="{% url 'app:dashboard' %}">Dashboard</a></li>
                    <li class="breadcrumb-item"><a href="{% url 'app:order' %}">Order</a></li>
                    <li class="breadcrumb-item active">Order Detail</li>
                </ol>
            </div>
            <h4 class="page-title">Order Detail</h4>
        </div>
    </div>
</div>

<div class="row justify-content-center pt-3">
    <div class="col-lg-8">
        <div class="card">
            <div class="card-body">
                <h4 class="header-title mb-3">Track Order</h4>

                <div class="row">
                    <div class="col-lg-6">
                        <div class="mb-4">
                            <h5 class="mt-0">Customer:</h5>
                            <p>{{order.fullname}}</p>
                        </div>
                    </div>
                    <div class="col-lg-6">
                        <div class="mb-4">
                            <h5 class="mt-0">Description:</h5>
                            <p>{{order.description}}</p>
                        </div>
                    </div>
                </div>

                <div class="track-order-list">
                    <ul class="list-unstyled">
                        <li class="completed">
                            <h5 class="mt-0 mb-1">Order Placed</h5>
                            <p class="text-muted">{{order.created_date}} </p>
                        </li>
                        <li class="completed">
                            <h5 class="mt-0 mb-1">Service</h5>
                            <p class="text-muted">{{order.service}} </p>
                        </li>

                        <li class="completed">
                            <h5 class="mt-0 mb-1">Order Start</h5>
                            <p class="text-muted">{{order.date_start}}</p>
                        </li>




                        {% if order.status == 'Delivery' %}
                        <li class="completed">
                            <span class="active-dot dot"></span>
                            <h5 class="mt-0 mb-1">Order Delivery</h5>
                            <p class="text-muted">{{order.date_delivery}}</p>
                        </li>
                        <li class="completed">
                            <h5 class="mt-0 mb-1"> Order Status</h5>
                            <p class="text-muted">{{order.status}}</p>
                        </li>
                        {% else %}
                        <li>
                            <span class="active-dot dot"></span>
                            <h5 class="mt-0 mb-1">Order Delivery</h5>
                            <p class="text-muted">{{order.date_delivery}}</p>
                        </li>
                        <li>
                            <h5 class="mt-0 mb-1"> Order Status</h5>
                            <p class="text-muted">{{order.status}}</p>
                        </li>
                        {% endif %}

                    </ul>

<!--                    <div class="text-center mt-4">-->
<!--                        <a href="#" class="btn btn-primary">Show Details</a>-->
<!--                    </div>-->
                </div>

            </div>
        </div>
    </div>

</div>

{% endblock content %}